automatictest:
  testfolder:
  forceListTestsName: Simple User Task
  exitAfterExecution: true


zeebe:
  client:
    security:
      plaintext: "true"
    broker:
      gateway-address: 127.0.0.1:26500
    request-timeout: PT60S

    saas:
      register:
      region:
      clusterid:
      clientid:
      clientsecret:

operate:
  client:
    base-url: http://localhost:8081
    authentication:
      simple:
        username: demo
        password: demo
tasklist:
  client:
    base-url: http://localhost:8082



camunda7:
  client:
    base-url: http://localhost:8080
    rest-api-context: engine-rest
    check-on-init: true

server.port: 8086